/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import classes.Aluno;
import classes.Emprestado;
import classes.Livro;
import classes.Professor;
import connection.AlunoDAO;
import connection.EmprestadoDAO;
import connection.LivroDAO;
import connection.ProfessorDAO;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Devolucao extends javax.swing.JFrame {
    LocalDate localDate = LocalDate.now();
    DateTimeFormatter format = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    String dataAtual = localDate.format(format);
    Aluno a = new Aluno();
    Professor p = new Professor();
    Livro l = new Livro();
    /**
     * Creates new form Devolucao
     */
    public Devolucao() {
        initComponents();
        initComponents();
        //Recebe a data atual como valor padrão no campo de texto
        this.tfDataA.setText(dataAtual);
        this.tfDataD.setText(dataAtual);
        //Se nenhum radio button foi selecionado, não permite alterações 
        cbAluno.setEditable(false);
        cbProfessor.setEditable(false);
        //Prenche os combobox
        preencheListaA();
        preencheListaP();
        preencheLivros();
    }
    
    /**
     * Limpa os campos
     */
    public void limparCampos(){
        this.tfCodigo.setText("");
        this.tfDataD.setText("");
        this.tfDataA.setText("");
        this.buttonGroup1.clearSelection();
        this.cbAluno.setSelectedIndex(0);
        this.cbProfessor.setSelectedIndex(0);
        this.cbLivro.setSelectedIndex(0);
    }
    
    /**
     * Preenche o combo box com Alunos
     */
    public void preencheListaA(){
        EmprestadoDAO ea = new EmprestadoDAO();
        ArrayList<Emprestado> emprestado_alunos = new ArrayList<>();
        emprestado_alunos = ea.buscarEmprestadoA();
        for(int i=0; i<emprestado_alunos.size(); i++){
            this.cbAluno.addItem(Integer.toString(emprestado_alunos.get(i).getAluno()));
        }
    }
    
    /**
     * Preenche o combo box com Professores
     */
    public void preencheListaP(){
        EmprestadoDAO ep = new EmprestadoDAO();
        ArrayList<Emprestado> emprestado_professores = new ArrayList<>();
        emprestado_professores = ep.buscarEmprestadoP();
        for(int i=0; i<emprestado_professores.size(); i++){
            this.cbAluno.addItem(Integer.toString(emprestado_professores.get(i).getProfessor()));
            System.out.println("Nome: "+emprestado_professores.get(i).getProfessor());
        }
    }
    
    /**
     * Preenche o combo box com Livros
     */
    public void preencheLivros(){
        LivroDAO l = new LivroDAO();
        ArrayList<Livro> livros = new ArrayList<>();
        livros = l.buscarTodos();
        for(int i=0; i<livros.size(); i++){
            this.cbLivro.addItem(livros.get(i).getTítulo());
        }
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        rbProfessor = new javax.swing.JRadioButton();
        rbAluno = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        tfCodigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfDataD = new javax.swing.JFormattedTextField();
        tfDataA = new javax.swing.JFormattedTextField();
        btRegistrar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cbLivro = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cbAluno = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cbProfessor = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Devolução");

        buttonGroup1.add(rbProfessor);
        rbProfessor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbProfessor.setText("Professor");

        buttonGroup1.add(rbAluno);
        rbAluno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbAluno.setText("Aluno");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Código");

        tfCodigo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCodigoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Data de Devolução");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Data Atual");

        tfDataD.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        tfDataD.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        tfDataA.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        tfDataA.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btRegistrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btRegistrar.setText("Registrar");
        btRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistrarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Livro");

        cbLivro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Aluno");

        cbAluno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Professor");

        cbProfessor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(rbProfessor)
                        .addGap(18, 18, 18)
                        .addComponent(rbAluno))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5))
                        .addGap(85, 85, 85)
                        .addComponent(tfDataA, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(cbProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfDataD, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btRegistrar)
                .addGap(153, 153, 153))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbProfessor)
                    .addComponent(rbAluno))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cbAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(cbProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfDataD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfDataA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(btRegistrar)
                .addGap(74, 74, 74))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCodigoActionPerformed

    private void btRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistrarActionPerformed
        String codigo;
        LocalDate dataD, dataA;
        String livro;
        String aluno;
        String professor;
        final DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        Emprestado e = new Emprestado();
        ProfessorDAO pd = new ProfessorDAO();
        AlunoDAO ad = new AlunoDAO();
        
        //Se nenhum radio button foi selecionado não permite alterações
        if(this.rbAluno.isSelected() == false && this.rbProfessor.isSelected() == false){
            JOptionPane.showMessageDialog(this, "Você deve preencher todos os campos!", "Erro", JOptionPane.ERROR_MESSAGE);
        }else{
            //Leitura dos campos
            codigo = this.tfCodigo.getText();
            dataD = LocalDate.parse(this.tfDataD.getText(), dtf);
            dataA = LocalDate.parse(this.tfDataA.getText(), dtf);
            
            //Se for de tipo Professor, cadastra como o tipo
            if(this.rbProfessor.isSelected()){
                professor = this.cbProfessor.getSelectedItem().toString();
                livro = this.cbLivro.getSelectedItem().toString();
                long multa = 0;
                
                //Verifica se campos estão preenchidos
                if(codigo.equals("") || dataD.equals("") || dataA.equals("")){
                    JOptionPane.showMessageDialog(this, "Você deve preencher todos os campos!", "Erro", JOptionPane.ERROR_MESSAGE);
                }else{
                    //Cadastro da devolucao
                    Livro l = new Livro();    
                    
                   // e.multar(professor, "Professor", dataA);
                    
                    l.realizarDevolução(Integer.parseInt(codigo), professor, livro, dataD, dataA);
                 
                    JOptionPane.showMessageDialog(this, "Devolução cadastrada com sucesso!");
                    this.limparCampos();
                }
            }
            //Se for tipo Aluno, cadastra como o tipo
            if(this.rbAluno.isSelected()){
                aluno = this.cbAluno.getSelectedItem().toString();
                livro = this.cbLivro.getSelectedItem().toString();
                long multa = 0;
                //Verifica os campos
                if(codigo.equals("") || dataD.equals("") || dataA.equals("")){
                    JOptionPane.showMessageDialog(this, "Você deve preencher todos os campos!", "Erro", JOptionPane.ERROR_MESSAGE);
                }else{
                    //Cadastra a devolução
                    Livro l = new Livro();  
                    
                    //e.multar(aluno, "Aluno", dataA);
            
                    l.realizarDevolução(Integer.parseInt(codigo), aluno, livro, dataD, dataA);
                    
                    if(multa==0){
                        JOptionPane.showMessageDialog(this, "Devolução cadastrada com sucesso!\n Não há multa!");
                        this.limparCampos();
                    }else{
                        JOptionPane.showMessageDialog(this, "Devolução cadastrada com sucesso!\n Multa: "+multa);
                        this.limparCampos();
                    }
                }
            }
        }
    }//GEN-LAST:event_btRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Devolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Devolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Devolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Devolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Devolucao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRegistrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbAluno;
    private javax.swing.JComboBox<String> cbLivro;
    private javax.swing.JComboBox<String> cbProfessor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton rbAluno;
    private javax.swing.JRadioButton rbProfessor;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JFormattedTextField tfDataA;
    private javax.swing.JFormattedTextField tfDataD;
    // End of variables declaration//GEN-END:variables
}
